### ISSUE TITLE
空指针

### ISSUE THREAD

**Issue by latemb** [Jidcoo/CommentView#1]
默认样式act 手动添加一条评论  点击回复空指针闪退 必先哈

**Comment by Jidcoo** [comment]
嗯，刚刚看了看，  
  
 对于第二个问题：    
这个问题是AdapterOperator.getReplies()方法缺少了判空步骤。  
  
这两个问题都会在下一个版本解决。但是估计到发布要等一段时间了。

**Comment by Jidcoo** [comment]
感谢反馈。期待未知的2.0版本：》
