### ISSUE TITLE
滑动冲突

### ISSUE THREAD

**Issue by latemb** [Jidcoo/CommentView#2]
嵌套ScrollView 或者recycleerView 滑动冲突

**Comment by Jidcoo** [comment]
嗯，
对于这个问题：  
其实本质上CommentView是一个LinearLayout,在这个线性布局上又包含了一个SwipeRefreshLayout，用来简单实现的上拉刷新需求。真正的数据展示控件是SwipeRefreshLayout内的ExpandableListView，所以与ListView相关的类似的所有嵌套、滑动问题都会在CommentView这个控件出现。
嗯，这其实就是一个很不好的地方，也是不好解决的问题。这些问题导致CommentView不容易被嵌套，很多时候只适用在单布局场景。目前我已经对CommentView的整个控件底层方面做了大调整，能够适配嵌套的需求。但是还没有太多的时间把它从项目中分离出来。发布最新版本可能要等一段时间了。
所以在目前这个阶段，你可以尝试一下用解决ListView嵌套问题的方案和思想来解决这个问题或改造CommentView，再嵌入你当前的项目中。
你对CommentView的控件的底层实现有什么好的idea吗？一起讨论讨论。

**Comment by Jidcoo** [comment]
旧架构下使用ExpandableListView实现导致嵌套滑动问题，新架构使用了自定义ViewGroup实现，解决了此问题，但新架构的控件库暂时不能开源。如果可以，到时候会以2.0为版本号更新控件库。
