### ISSUE TITLE
视图为空，没报错，有数据

### ISSUE THREAD

**Issue by as2651608102** [Jidcoo/CommentView#4]
视图为空，没报错，有数据，这种是怎么解决

**Comment by Jidcoo** [comment]
CommentView的构造方法：
public CommentView(Context context, ViewGroup attachTo)

第一个参数是Activity的上下文。第二个参数是ViewGroup，也就是将控件挂靠在这个指定的布局上。注意：当attachTo参数为空时，需要手动把控件添加到布局中，否则控件将不会显示。

初始化回调（非常重要，必须初始化）：

无论是否需要设置回调，都要调用.buildCallback()方法完成初始化。

并且初始化回调的工作必须要在loadComplete()方法调用之前（即首次加载数据之前）完成，否则控件将无法正常使用。


------------------------
具体请查看博客：https://blog.csdn.net/qq_33794872/article/details/107163983
