### ISSUE TITLE
本地回复数据如何处理分页,分页逻辑后台没有给的情况下

### ISSUE THREAD

**Issue by Chenshuai770** [Jidcoo/CommentView#7]
replies回复类的数据如果不请求接口,replies一开始就返回了固定数据,比如12条,怎么做出分页的效果,比如回复默认只显示一条,点击展开更多回复显示全部数据?

**Comment by Jidcoo** [comment]
一般来说，你可以获取到数据后再来完成bean中分页属性的填充

**Comment by Jidcoo** [comment]
process end
